baseURL = "https://altairshmily.github.io/"
defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"
title = "Altair's Blog"
theme = "blowfish"

[pagination]
  enableRobotsTXT = true
  buildDrafts = false
  paginate = 20
  summaryLength = 30

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

